- name: Fazer o DESTROY das aplicações
  hosts: localhost
  tasks:
      
    #Cluster
    - name: Entrar no Cluster
      shell: "gcloud container clusters get-credentials lais-clustergke-df --region us-east1 --project ces-igniteprogram"
    
    #Certificado       
    - name: DESTROY namespace para o gerenciador do certificado
      shell: "kubectl delete namespace cert-manager"
    
    #Ingress-controller
    - name: Deletar a namespace deploy-ingress
      shell: "kubectl delete namespace deploy-ingress"


    