- name: Fazendo o deploy do Wordpress
  hosts: localhost
  tasks:
    - name: Entrar no Cluster
      shell: "gcloud container clusters get-credentials lais-clustergke-df --region us-east1 --project ces-igniteprogram"
      
    - name: Criar um namespace
      shell: "kubectl apply -f namespace.yaml"

    - name: Instalar o wordpress
      shell: "helm install my-wordpress bitnami/wordpress --version 16.0.4 -n deploy-wordpress"

    - name: Entrar na pasta do hpa
      shell: "cd /desafio-final/kubernetes-ingress/deployments/helm-chart/templates"

    - name: Executar o hpa
      shell: "kubectl apply -f hpa.yaml"